# Generated by Django 6.1 on 2026-09-06 07:02

import django.contrib.postgres.constraints
from django.db import migrations, models

import clinic.models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_enable_btree_gist"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                expressions=[
                    (clinic.models.TsTzRange("start_time", "end_time"), "&&"),
                    ("doctor", "="),
                ],
                name="exclude_overlapping_appointments",
            ),
        ),
    ]
